server:
  port: 9192
spring:
  data:
    mongodb:
      uri: mongodb+srv://bhushan:Bhushan@cluster0.ryjta.mongodb.net/guest?retryWrites=true&w=majority
  application:
    name: Guest-Service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost