server:
  port: 9191
spring:
  data:
    mongodb:
      uri: mongodb://bhushan:Bhushan@cluster0-shard-00-00.gcssq.mongodb.net:27017,cluster0-shard-00-01.gcssq.mongodb.net:27017,cluster0-shard-00-02.gcssq.mongodb.net:27017/hotelEMP?ssl=true&replicaSet=atlas-3pwx3m-shard-0&authSource=admin&retryWrites=true&w=majority
  application:
    name: Employee-Service
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eureka
  instance:
    hostname: localhost